per_listener_settings true
retain_available false

listener 8883 0.0.0.0
protocol mqtt
allow_anonymous false
require_certificate true
use_identity_as_username true
use_username_as_clientid true
max_qos 1
cafile /run/secrets/mqtt_ca
crlfile /run/secrets/mqtt_crl
certfile /run/secrets/mqtt_server_certificate
keyfile /run/secrets/mqtt_server_private_key
tls_version tlsv1.2
acl_file /mosquitto/config/acl

persistence true
persistence_location /mosquitto/data/
autosave_interval 60
autosave_on_changes false
persistent_client_expiration 14d
max_queued_messages 1000
message_size_limit 1048576

log_dest stdout
log_type error
log_type warning
log_type notice
connection_messages true
